[package]
name = "chip8"
version = "0.1.0"
authors = ["Cedric Legendre <cedric.legendre@epitech.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.15.0"
strum_macros = "0.15.0"
